server:
  port: 8080

# database
spring:

  datasource:
    url: jdbc:mysql://49.50.161.155:3306/doruri_database?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true

oauth2:
  kakao:
    client-id: 36f934df3a644d54650fb1fc8f9b81ad
    client-secret: YTXwdlZWX144zrdJJvIHrQknJXy6f4dP