server:
  port: 8080

# database
spring:

  datasource:
    url: jdbc:mysql://49.50.161.155:20005/doruri_database?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
      ejb:
        naming_strategy: ImprovedNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true


oauth2:
  kakao:
    client-id: 2d960674477423e2305b22da427a9338
    client-secret: YTXwdlZWX144zrdJJvIHrQknJXy6f4dP